name: Build Profiles

on:
  push:
    paths:
      - "**.fsh"
      - "**/sushi-config.yaml"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: profiles
      - name: Get FHIR packages
        uses: cybernop/get-fhir-packages@v1
      - name: Update FHIR Profiles
        uses: cybernop/update-fhir-profiles@main
        with:
          sushi-version: "3.0.0-beta.1"
          working-directory: profiles
